//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeifenLuo.WinFormsUI.ThemeVS2005 {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeifenLuo.WinFormsUI.ThemeVS2005.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Docking ähnelt.
        /// </summary>
        internal static string Category_Docking {
            get {
                return ResourceManager.GetString("Category_Docking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Docking Notification ähnelt.
        /// </summary>
        internal static string Category_DockingNotification {
            get {
                return ResourceManager.GetString("Category_DockingNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Property Changed ähnelt.
        /// </summary>
        internal static string Category_PropertyChanged {
            get {
                return ResourceManager.GetString("Category_PropertyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Determines if end user drag and drop docking is allowed. ähnelt.
        /// </summary>
        internal static string DockContent_AllowEndUserDocking_Description {
            get {
                return ResourceManager.GetString("DockContent_AllowEndUserDocking_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The size to display the content in auto hide mode. Value &lt; 1 to specify the size in portion; value &gt;= 1 to specify the size in pixel. ähnelt.
        /// </summary>
        internal static string DockContent_AutoHidePortion_Description {
            get {
                return ResourceManager.GetString("DockContent_AutoHidePortion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable/Disable the close button of the content. ähnelt.
        /// </summary>
        internal static string DockContent_CloseButton_Description {
            get {
                return ResourceManager.GetString("DockContent_CloseButton_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gets or sets a value indicating in which area of the DockPanel the content allowed to show. ähnelt.
        /// </summary>
        internal static string DockContent_DockAreas_Description {
            get {
                return ResourceManager.GetString("DockContent_DockAreas_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Occurs when the value of DockState property changed. ähnelt.
        /// </summary>
        internal static string DockContent_DockStateChanged_Description {
            get {
                return ResourceManager.GetString("DockContent_DockStateChanged_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Indicates the content will be hidden instead of being closed. ähnelt.
        /// </summary>
        internal static string DockContent_HideOnClose_Description {
            get {
                return ResourceManager.GetString("DockContent_HideOnClose_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The desired docking state when first showing. ähnelt.
        /// </summary>
        internal static string DockContent_ShowHint_Description {
            get {
                return ResourceManager.GetString("DockContent_ShowHint_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Context menu displayed for the dock pane tab strip. ähnelt.
        /// </summary>
        internal static string DockContent_TabPageContextMenu_Description {
            get {
                return ResourceManager.GetString("DockContent_TabPageContextMenu_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The tab text displayed in the dock pane. If not set, the Text property will be used. ähnelt.
        /// </summary>
        internal static string DockContent_TabText_Description {
            get {
                return ResourceManager.GetString("DockContent_TabText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The text displayed when mouse hovers over the tab. ähnelt.
        /// </summary>
        internal static string DockContent_ToolTipText_Description {
            get {
                return ResourceManager.GetString("DockContent_ToolTipText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Context menu displayed for the dock pane tab strip. ähnelt.
        /// </summary>
        internal static string DockHandler_TabPageContextMenuStrip_Description {
            get {
                return ResourceManager.GetString("DockHandler_TabPageContextMenuStrip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press SHIFT for docking to full side. ähnelt.
        /// </summary>
        internal static string DockIndicator_ToolTipText {
            get {
                return ResourceManager.GetString("DockIndicator_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FloatWindow property can not be set to &quot;null&quot; when DockState is DockState.Float. ähnelt.
        /// </summary>
        internal static string DockPane_FloatWindow_InvalidValue {
            get {
                return ResourceManager.GetString("DockPane_FloatWindow_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto Hide ähnelt.
        /// </summary>
        internal static string DockPaneCaption_ToolTipAutoHide {
            get {
                return ResourceManager.GetString("DockPaneCaption_ToolTipAutoHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        internal static string DockPaneCaption_ToolTipClose {
            get {
                return ResourceManager.GetString("DockPaneCaption_ToolTipClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        /// </summary>
        internal static string DockPaneCaption_ToolTipOptions {
            get {
                return ResourceManager.GetString("DockPaneCaption_ToolTipOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        internal static string DockPaneStrip_ToolTipClose {
            get {
                return ResourceManager.GetString("DockPaneStrip_ToolTipClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Window List ähnelt.
        /// </summary>
        internal static string DockPaneStrip_ToolTipWindowList {
            get {
                return ResourceManager.GetString("DockPaneStrip_ToolTipWindowList", resourceCulture);
            }
        }
    }
}
